### ISSUE TITLE
Partial update not working for test/election and admin/election

### ISSUE THREAD

**Issue by xsicp01** [CA-elections/backend#28]
When using the partial update call for test/election and admin/election, we are unable to leave out the candidates field. When using [] the candidates get overridden. And when not supplying the field, it throws an error:
File "C:\Users\CaField\Ca-elections\backend\api\serializers.py" in update
  292.         candidates_data = validated_data.pop('candidates')

Exception Type: KeyError at /api/admin/election/1/
Exception Value: 'candidates'

**Comment by lesves** [comment]
It's a really serious bug, bois!
Achtung!

**Comment by lesves** [comment]
Bois, some dank memez: [https://i.imgflip.com/1xvke8.jpg](url)

**Comment by lesves** [comment]
Tak seš černej?
